travis:
  secure:
    BINSTAR_TOKEN: KH0ZiNFwhwnACrZjciiN+0SiNWZUo4FmTf6PMIKawjUBPAwN6vXGvq2DW7cIHxXntsJY4o/n0pe9Uxg/hDYMs4mk1L19I/0XziLV53jAUhoxywmaCOI0iMc3sDTHPxt1ulEulUrWqDMLojAOctEsEpQH8Q1Jz/BECOoxd/8Okw6oa6UnidHfM4Pu8LX7Fh7Pi1lbN9NL+wDaG9JUY6lBlf6pEHmv/9pb8ckNI/WOxernzrx/Xo8KdE1jxZwW+qwD9I5hkfzH25iU3OW+UjqfcE2Sw6bE6KkPwTnfAZDI+Ih1BHRkWqDaQD96drVT1Qo2Dz3GLs3W90fDdWOB1LYFxSFJuVP0rye5pYeb2MtuNuGbYtVV3Dd7+KakxMxU14236znnQAvX7CSW2JFlj8wCHZUp15V4+2OfQZSVHhI2Wb4173W5PCDzrQgl4H+ExWEzMlVUXLsYEarrUBUOjpG9AHKuprBFd2C2V/Tsh1bID5DzgJc7zilxBbfXpudmw/k/51M9TeSIBesJkNJ9m2rtTnqxYCoPu55FUu9i3h/Efs/0Z0YMDzOpBqNbRQp593r83wtZS1AmPazyMuBV+iWAFt4JmYvCHLnHoORzznqDuBRGSJXtpX88NQY2t9FeaAnbdWbxZuRLXPHh4NGntxFMbnlptteBDFaK11rUsIeqtj4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
