travis:
  secure:
    BINSTAR_TOKEN: Vy1XgQOWoUuC+GBcCpTMfrcnLw6/MPMQ4Op9mnpun7YWfPcaT6O/ZcDhCXvf2tzY5bpLJn1F/h+m97DY/niFLvNulnFoSK8VK3AQ3uqtc9r7vNf0jhP9q19UrhtA9SNE/V1np5/PhGD66CGX+OsDPyMn81Skylrco67DDYtXT2tNhma/KQllWhbrD+ab+YHyJ3oH2EUl/8ad58T2Z0/FfyNXrkhJ1eB08irIrJ/qBt2aJS74CDG/bbfZJgaAQ/WKZF7CeaV/eAStw5kX7Zh9aX7cGRmmvNm4Yf99oklRJOJ0Kz3x6tJc/U4nW95UYA9CR+naibKYLuCaBGHjZlZcpBM5vaZAqjyOymVr1hALpXFi6e0QerpTHa7FPe+nlKjsvuu/pVOMq81/WDWvJp8JPxuEKFuVRumfLxaD7olIkz3A1vdQg/MbiZdXx1yu2MiQHzqCNURH+f8NFjiboRi6HEReSSRWYbXi5sHAoSO6GpBL3ZemHQH9KFfdAtb/QKUPpIgjd0IojVxBZh63quiKUyJFM3KH/SSnKsFA3mlbIV4YEu+kkkBqbFEo0ssypqZVkvjPrDfERMVMV/2nYE0l1Pvaw9MTmuy6KraJstsGmv12NwM4ed1UoDHh7MmsvKI1IOSVR1QVkQEnBuT/tNpuytbsO5ROBOVgRnHR4phY8Ag=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
