travis:
  secure:
    BINSTAR_TOKEN: zabcqJ5D6/+qUJ12f7+ieJafJ+5SKG+GCy0CKZWvlz7+V44F8vFn9aM93qNr19RoDwQ+zLXhstIi4BjKY+ZDfDSXE4pVp5/QBuUU9t1+paVQ4Xjvi8ig4s8JpSqqhFbOtpUbQB1uXvzZicI9rwA3Cr6zfz85sOatARIlKz5yMv5xk8ehb0W2L5tYbrHVYwDdF7zl60u9bvvaEd+Q5YcUyZbrDppcfIEOtlGWInh3pmplS8QAL49hTB1HQwS600oE0gW4O2+9fShZ7JDMVv9UpbH2CYarYip7DEofNIcdza++pRgsUjrFZGvFj9bQPyOlK3cwsk59Qhj9udHvdBINqN06wTs1Oll8qtuKNp6jFhflL+NMXjdj6FOzprUlZgeuWFJX4+VFnxQHZxTKDHsVLCAZW7AClkIyenV1disvc+jHTtTZhMFp30oEWX+k23L4jMtzEcw2UiI9ktcMJOEeTWxSUNBtyzqGMcggJbU+t70D8TZV07NMI6RuCl+9Epk+svS4cY6kn7nLK44S5CD0pKOdpzoiH3AGTVW2hNKajzH7BchPftpkKV2FAnWDk63n9zQOfbZDivM4R5+/9p7Qiipi5zHGVcOSNASJUdx2m0oluTywkTyptQr4p0ZzK9Ldbtw1aDTExhZu70XDt3PkYU64fYGjQbRqn/Ih4d5blyM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
